### ISSUE TITLE
Package ready for use?

### ISSUE THREAD

**Issue by icejix** [AsahiLinux/asahi-audio#26]
Hi, sorry that this isn't an "issue", but I'd like to ask a question. Is this package ready to be used on consumer machines yet? I've noticed that the warning at the bottom was removed, and that got me pretty excited. If it's still not ready, I'd urge you to put it back there, so that people know that they shouldn't be using this yet.

I am only asking this question as I've looked into speakersafetyd and have noticed that it still has the warning and "eleven secret herbs and spices" text, while this one no longer has it.

Of course, thanks for what you do, and please feel free to close this issue as soon as you respond.

**Comment by chadmed** [comment]
speakersafetyd's readme no longer has any reference to that. We publicly released speaker support for the models listed here last week, so yes this is safe to use. You only need to update your system and it will all work.

**Comment by icejix** [comment]
Ah, okay. Thank you. Can you please provide guidance on how to do that? Sorry, I'm not sure where to ask.

**Comment by icejix** [comment]
@chadmed Sorry, I don't want to disturb you, but I do want to enable speaker support. I can't figure it out. I've tried manually installing the package, but it hasn't worked. (I was running `make all` and `sudo make install` in speakersafetyd and asahi-audio). I don't know where else to ask, and if the speakers are ready, I would really like to use them. The README contains some things about "LSP Plugins" and "asahi-linux 6.6-11", but I can't find either of these things. Help would be appreciated!

**Comment by chadmed** [comment]
Which distro are you on? It should have been automatic for Fedora on the next upgrade

**Comment by icejix** [comment]
Hi there, I was able to figure it out around a week ago. I just reinstalled Fedora, and it worked fine.

**Comment by MadokaIII** [comment]
Wait i'm starting to become paranoid.
 I reinstalled fedora 5000 times and tinkered with speakersafetyd and tas2764 (because both weren't activated by default);
 I installed every alsa packages remotely related, tried with every combination of them, checked wireplumber and pipewire and bankstown, checked asahi-plateform-metapackage-audio, asahi-audio;
 I checked asahi-diagnose, alsa-info.sh, alsamixer which never detected a soundcard and asahi-diagnose had platform sound deferred probing or something like that i don't quite remember;
 and throught all that NEVER has speakersafetyd been launched on boot even after enabling it with systemctl and modprobing tas2764 and macaudio which wasn't activated for some reason.
How did you do it what kind of black magic did you use, everyone here seems to have been able to activate them except me.
Help would be very much appreciated, I'm on a Macbook Air M1.
I'll add asahi-diagnose output and alsa-info also, I just don't have the time right but needed to post this message, it's been a week that I've been refraining from asking online because everyone made it work out of the box on install. 
It felt stupid that I couldn't for some reason.

**Comment by MadokaIII** [comment]
[asahi-diagnose-20240108-095728.txt](https://github.com/AsahiLinux/asahi-audio/files/13858477/asahi-diagnose-20240108-095728.txt)

http://alsa-project.org/db/?f=8a29c8a638e811d0ab526aa19f4fc4b47e09948e

Here are the logs I was talking about.
I hope you guys can help me.

**Comment by chadmed** [comment]
Please don't hijack closed issues. Open a new one.

**Comment by MadokaIII** [comment]
Sorry, I'll do just that.
