### ISSUE TITLE
All audio broken

### ISSUE THREAD

**Issue by 1vanKa** [AsahiLinux/asahi-audio#28]
Audio is completely broken on my MBP 16 2021 M1 Pro. I haven't turned off my computer for some days, just turned it into sleep, and today this happened. This sound is heard instead of all sounds in system, not only browser.

https://github.com/AsahiLinux/asahi-audio/assets/62416447/ac710ece-7836-4744-af38-034066a1b20c

Maybe you can place instruction somewhere how to restart sound system to fix this?

**Comment by chadmed** [comment]
Could you please paste the output of `asahi-diagnose` somewhere first

**Comment by 1vanKa** [comment]
[asahi-diagnose-20240106-151609.txt](https://github.com/AsahiLinux/asahi-audio/files/13849631/asahi-diagnose-20240106-151609.txt)

**Comment by 1vanKa** [comment]
Why does asahi-diagnose prints
`Pipewire macaudio profile is "none".
Headphones and speakers will not work. Select the "Default" or "HiFi" profile.`
But my speakers are working right now

**Comment by chadmed** [comment]
That's just a result of some faulty logic that will be fixed soon. If your speakers are working, there's no need to worry about that message.

The garbled audio is _probably_ due to codec chip shenanigans that we need to work through. The actual electrical configuration of these machines can be quite delicate and  needs careful handling. A similar effect can be produced from I2S problems so it may be that.

**Comment by 1vanKa** [comment]
Ok, thank you for the explanation. Can you write some instructions how audio system can be restarted without full laptop reboot if possible?

**Comment by chadmed** [comment]
For the particular issue you showed in your video, the only fix is to reboot.

**Comment by 1vanKa** [comment]
Got it, thank you.
