### ISSUE TITLE
Freeze when playing audio on speakers

### ISSUE THREAD

**Issue by automainint** [AsahiLinux/asahi-audio#52]
I have MacBook Air M2 with Asahi Fedora 41.
Recently audio via speakers stopped working.
Any application that tries to play audio freezes if it uses speakers.
If I plug in headphones and run `systemctl --user restart pipewire`, it restarts after some delay (~40 sec), and then audio works fine via headphones.

**Comment by chadmed** [comment]
This issue is due to the latest version of lsp-plugins being broken. Please downgrade it by running `dnf downgrade lsp-plugins-lv2` and rebooting. The next release will be fixed, and in the meantime an upstream patch has been backported and will be available in F41 by the time you next update your system :)

**Comment by automainint** [comment]
> Please downgrade it by running `dnf downgrade lsp-plugins-lv2` and rebooting.

Thanks, that worked.
